//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLClassifierStation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MLClassifierStation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        public static string Accuracy {
            get {
                return ResourceManager.GetString("Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fraction of all instances that are correctly categorized.
        ///It is the ratio of the number of correct classifications
        ///to the total number of correct or incorrect classifications
        ///ACC=(TP + TN)/(P+N).
        /// </summary>
        public static string AccuracyTooltip {
            get {
                return ResourceManager.GetString("AccuracyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balanced accuracy.
        /// </summary>
        public static string BalancedAccuracy {
            get {
                return ResourceManager.GetString("BalancedAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACC = (TP/P + TN/N)/2.
        /// </summary>
        public static string BalancedAccuracyTooltip {
            get {
                return ResourceManager.GetString("BalancedAccuracyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cohen&apos;s kappa.
        /// </summary>
        public static string CohensKappa {
            get {
                return ResourceManager.GetString("CohensKappa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The agreement between the actual conditions and the predictions.
        ///k=(Po - Pe)/(1 - Pe)
        ///where Po is accuracy and Pe is the hypothetical probability
        ///of chance agreement, using the observed data to calculate
        ///the probabilities of each observer randomly seeing each category.
        ///On complete agreement k=1.
        /// </summary>
        public static string CohensKappaTooltip {
            get {
                return ResourceManager.GetString("CohensKappaTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross validation.
        /// </summary>
        public static string CrossValidationScheme {
            get {
                return ResourceManager.GetString("CrossValidationScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1 Score.
        /// </summary>
        public static string F1Score {
            get {
                return ResourceManager.GetString("F1Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The measure of a test&apos;s accuracy.
        ///It is the harmonic mean of the precision and recall.
        ///Best value is 1, worst is 0.
        /// </summary>
        public static string F1ScoreTooltip {
            get {
                return ResourceManager.GetString("F1ScoreTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallout (False positive rate).
        /// </summary>
        public static string Fallout {
            get {
                return ResourceManager.GetString("Fallout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ratio of false positives and all negative items.
        ///FPR = FP / (TN + FP).
        /// </summary>
        public static string FalloutTooltip {
            get {
                return ResourceManager.GetString("FalloutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False discovery rate.
        /// </summary>
        public static string FalseDiscoveryRate {
            get {
                return ResourceManager.GetString("FalseDiscoveryRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ratio of false positives and all items predicted as positive.
        ///FDR = FP / (FP + TP).
        /// </summary>
        public static string FalseDiscoveryRateTooltip {
            get {
                return ResourceManager.GetString("FalseDiscoveryRateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False negative rate.
        /// </summary>
        public static string FalseNegativeRate {
            get {
                return ResourceManager.GetString("FalseNegativeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ratio of false negatives and all positive items.
        ///FNR = FN / (TP + FN).
        /// </summary>
        public static string FalseNegativeRateTooltip {
            get {
                return ResourceManager.GetString("FalseNegativeRateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folds count.
        /// </summary>
        public static string FoldsCount {
            get {
                return ResourceManager.GetString("FoldsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holdout percent.
        /// </summary>
        public static string HoldoutPercent {
            get {
                return ResourceManager.GetString("HoldoutPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holdout validation.
        /// </summary>
        public static string HoldoutValidationScheme {
            get {
                return ResourceManager.GetString("HoldoutValidationScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informedness.
        /// </summary>
        public static string Informedness {
            get {
                return ResourceManager.GetString("Informedness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informedness quantifies how informed a predictor is
        ///for the specified condition and specifies the probability
        ///that a prediction is informed in relation to the condition
        ///(versus chance).
        ///Informedness = sensitivity + specificity - 1.
        /// </summary>
        public static string InformednessTooltip {
            get {
                return ResourceManager.GetString("InformednessTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markedness.
        /// </summary>
        public static string Markedness {
            get {
                return ResourceManager.GetString("Markedness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markedness quantifies how marked a condition is
        ///for the specified predictor, and specifies the probability
        ///that a condition is marked by the predictor(versus chance).
        ///Markedness = Precision + Inverse Precision - 1.
        /// </summary>
        public static string MarkednessTooltip {
            get {
                return ResourceManager.GetString("MarkednessTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matthew&apos;s correlation coefficient.
        /// </summary>
        public static string MatthewsCorrelationCoefficient {
            get {
                return ResourceManager.GetString("MatthewsCorrelationCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It takes into account true and false positives and negatives.
        ///It is correlation coefficient between the observed
        ///and predicted binary classifications;
        ///it returns a value between −1 and +1.
        ///A coefficient of +1 represents a perfect prediction,
        ///0 no better than random prediction and −1 indicates
        ///total disagreement between prediction and observation.
        /// </summary>
        public static string MatthewsCorrelationCoefficientTooltip {
            get {
                return ResourceManager.GetString("MatthewsCorrelationCoefficientTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimization learning algorithm.
        /// </summary>
        public static string MLCS_MinimizationLearningAlgorithmPlugin {
            get {
                return ResourceManager.GetString("MLCS.MinimizationLearningAlgorithmPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative predictive value.
        /// </summary>
        public static string NegativePredictiveValue {
            get {
                return ResourceManager.GetString("NegativePredictiveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ratio of true negatives and all items that are predicted negative.
        ///NPV = TN / (TN + FN).
        /// </summary>
        public static string NegativePredictiveValueTooltip {
            get {
                return ResourceManager.GetString("NegativePredictiveValueTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimized precision.
        /// </summary>
        public static string OptimizedPrecision {
            get {
                return ResourceManager.GetString("OptimizedPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It takes into account accuracy, sensitivity and specificity.
        ///OP = Acc - |Sp - Sn|/(Sp + Sn).
        /// </summary>
        public static string OptimizedPrecisionTooltip {
            get {
                return ResourceManager.GetString("OptimizedPrecisionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision (Positive predictive value).
        /// </summary>
        public static string Precision {
            get {
                return ResourceManager.GetString("Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tha ratio of true positives and all items that are predicted positive.
        ///P = TP / (TP + FP).
        /// </summary>
        public static string PrecisionTooltip {
            get {
                return ResourceManager.GetString("PrecisionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recall (True positive rate, Sensitivity).
        /// </summary>
        public static string Recall {
            get {
                return ResourceManager.GetString("Recall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ratio of true positives and positive items.
        ///R = TP / (TP + FN).
        /// </summary>
        public static string RecallTooltip {
            get {
                return ResourceManager.GetString("RecallTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter is required.
        /// </summary>
        public static string RequiredParameter {
            get {
                return ResourceManager.GetString("RequiredParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specificity (True negative rate).
        /// </summary>
        public static string Specificity {
            get {
                return ResourceManager.GetString("Specificity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ratio of true negatives and negative items.
        ///Sp = TN / (TN + FP).
        /// </summary>
        public static string SpecificityTooltip {
            get {
                return ResourceManager.GetString("SpecificityTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuning factor.
        /// </summary>
        public static string TuningFactor {
            get {
                return ResourceManager.GetString("TuningFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuning percent.
        /// </summary>
        public static string TuningPercent {
            get {
                return ResourceManager.GetString("TuningPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncertainty coefficient.
        /// </summary>
        public static string UncertaintyCoefficient {
            get {
                return ResourceManager.GetString("UncertaintyCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a measure of the entropy in a column variable Y
        ///which a row variable X explains.
        ///Uncertainty coefficients range from 0 to 1.
        ///A low entropy means very strong correlation;
        ///a high entropy implies low correlation and so low uncertainty.
        /// </summary>
        public static string UncertaintyCoefficientTooltip {
            get {
                return ResourceManager.GetString("UncertaintyCoefficientTooltip", resourceCulture);
            }
        }
    }
}
